#!/usr/bin/env bash
## What is the OSI model & How is the OSI model organized
The OSI model is organized from the lowest to the highest level, with each layer building upon the functionality of the layer below it.
