#!/usr/bin/env bash
#This script configures an Ubuntu server with a few requirements on the task.
cp /etc/hosts /etc/hosts.new
echo "127.0.0.2  localhost"
echo "8.8.8.8  facebook.com"
cp -f /etc/hosts.new /etc/hosts
